sudo: required
services:
  - docker

before_install:
  - docker build -t prathamesh12/dockerfibo-tests -f ./client/Dockerfile.dev

scripts:
  - docker run prathamesh12/dockerfibo-tests CI=true npm run test

after_success:
  - docker build -t prathamesh12/dockerfibo-client ./client
  - docker build -t prathamesh12/dockerfibo-server ./server
  - docker build -t prathamesh12/dockerfibo-worker ./worker
  - docker build -t prathamesh12/dockerfibo-ngnix ./ngnix
