sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t prathamesh12/dockerfibo-test -f ./client/Dockerfile.dev ./client

script:
  - docker run prathamesh12/dockerfibo-test -e CI=true npm run test

after_success:
  - docker build -t prathamesh12/dockerfibo-client ./client
  - docker build -t prathamesh12/dockerfibo-server ./server
  - docker build -t prathamesh12/dockerfibo-worker ./worker
  - docker build -t prathamesh12/dockerfibo-ngnix ./ngnix

  #login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER_ID" --password-stdin

  #push to docker-hub
  - docker push prathamesh12/dockerfibo-client
  - docker push prathamesh12/dockerfibo-server
  - docker push prathamesh12/dockerfibo-worker
  - docker push prathamesh12/dockerfibo-ngnix

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'dockerfibo'
  env: 'Dockerfibo-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-812122552477'
  bucket_path: 'dockerfibo'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
